grid:
  model.dim_model: [16, 32]
  model.num_layers: [1, 2]
  model.window_size: [100, 200]
  model.use_current_feature: [True, False]
  model.calibration_size: [100, 500]
  model.similarity_fn: ["dot_product", "cos_similarity"]
  data.strided_features: ["xr", "xry"]


tuning:
  num_sequences: 2
  delta_threshold: -0.01