data:
  data_path: "./data/air-10_prediction/lr/lr_air-10_data.pkl"  
  calibration_ratio: 0.66


model:
  rho: 0.99
  max_past: 500
  target_quantiles:
    - [0.05, 0.95]


plotting:
  plotting: True
  plotting_seq_len: 200

saving_dir: "./results/nexcp/air/lr/"