data:
  data_path: "C:/Users/jayao/Desktop/base_predictor/lr_toy_data.pkl"
  train_ratio: 0.6
  valid_ratio: 0.1
  normalize: False


model:
  n_estimators: 10
  max_depth: 2
  criterion: "squared_error"
  target_quantiles:
    - [0.950, 0.05]
  prediction_step: 1
  window_size: 50


saving_dir: "C:/Users/jayao/Desktop/spci_test/"

