device: 0


data:
  data_path: "C:/Users/jayao/Desktop/base_predictor/lr_toy_data.pkl"
  train_ratio: 0.6
  valid_ratio: 0.2
  normalize: True
  shifted_concatenation: False
  strided_features: "xr"


model:
  dim_model: 4
  num_head: 4
  num_layers: 4
  dropout: 0.
  target_quantiles:
    - [0.950, 0.05]
  prediction_step: 1
  window_size: 200


training:
  batch_size: 8
  learning_rate: 0.001
  epochs: 100
  early_stop: 2

saving_dir: "C:/Users/jayao/Desktop/run_test/"

