
device: 0

data:
  data_path: "C:/Users/jayao/Desktop/base_predictor/ridge_toy_data.pkl"
  train_ratio: 0.35
  valid_ratio: 0.35
  normalize: False
  memory_features: "xy"


model:
  dim_context_encoding: 2
  dim_hopfield_hidden: 2
  beta: 1
  memory_size: 300
  prediction_step: 1
  alpha: 0.1
  sampling_num: 1000


training:
  batch_size: 16
  learning_rate: 0.01
  epochs: 2000
  validation_epochs: 5

saving_dir: "C:/Users/jayao/Desktop/run_test/"

