grid:
  model.shared_dim: [16, 32]
  model.num_heads: [2, 4]
  model.num_layers: [2, 4]
  model.use_current_feature: [True, False]
  model.window_size: [100, 200]
  data.strided_features: ["xr", "xry"]
  training.learning_rate: [0.0001, 0.001]


tuning:
  num_sequences: 2
  delta_threshold: -0.01