device: 0


data:
  data_path: "./data/air-10/chronos/chronos_air-10_data.pkl"
  train_ratio: 0.7
  valid_ratio: 0.15
  normalize: True
  strided_features: "xry"


model:
  dim_model: 32
  num_heads: 2
  num_layers: 2
  dropout: 0.
  use_current_feature: True
  target_quantiles:
    - [0.05, 0.950]
  prediction_step: 1
  window_size: 100
  calibration_size: 100
  similarity_fn: "dot_product"
  temperature: 1
  sampling_num: 1000


training:
  batch_size: 32
  learning_rate: 0.0001
  epochs: 1
  early_stop: 1

plotting:
  plotting: True
  plotting_seq_len: 200


saving_dir: "./results/run_test_lcp_transformer/"

