
device: 0


data:
  data_path: "./data/air-10_prediction/chronos/chronos_air-10_data.pkl"
  train_ratio: 0.6
  valid_ratio: 0.2
  normalize: True
  strided_features: "xr"


model:
  rnn_type: "lstm"
  dim_model: 64
  num_layers: 2
  dropout: 0.
  use_current_feature: True
  target_quantiles:
    - [0.05, 0.95]
  prediction_step: 1
  window_size: 100


training:
  batch_size: 64
  learning_rate: 0.001
  epochs: 1
  early_stop: 2


plotting:
  plotting: True
  plotting_seq_len: 200


saving_dir: "./results/run_test_rnn/"

