data:
  data_path: "./data/solar_prediction/lstm/lstm_nsdb-60m_data.pkl"
  train_ratio: 0.66
  normalize: true

model:
  optimize_beta: true
  beta_bins: 5
  n_estimators: 10
  max_depth: 50
  criterion: "squared_error"
  target_quantiles:
    - [0.975, 0.025]
  prediction_step: 1
  window_size: 100

plotting:
  plotting: true
  plotting_seq_len: 200

saving_dir: "./results/spci/solar/lstm/${now:%Y-%m-%d_%H-%M-%S_%f}/"
