data:
  data_path: "./data/air-10_prediction/lstm/lstm_air-10_data.pkl"
  train_ratio: 0.66
  # test = heldout * (1 - train_ratio)
  normalize: True


model:
  optimize_beta: true
  beta_bins: 5
  n_estimators: 10
  max_depth: 50
  criterion: "squared_error"
  target_quantiles:
    - [0.950, 0.05]
  prediction_step: 1
  window_size: 100


plotting:
  plotting: True
  plotting_seq_len: 200
  
  
saving_dir: "./results/spci/air/lstm/"