data:
  data_path: "./data/sapflux-solo3-large/lr/lr_sapflux-solo3-large_data.pkl"
  train_ratio: 0.66
  normalize: true

model:
  n_estimators: 10
  max_depth: 2
  criterion: "squared_error"
  target_quantiles:
    - [0.95, 0.05]
  prediction_step: 1
  window_size: 100

plotting:
  plotting: true
  plotting_seq_len: 200

saving_dir: "./results/spci_lr_sapflux/"
