data:
  data_path: "./data/sapflux-solo3-large/lstm/lstm_sapflux-solo3-large_data.pkl"
  train_ratio: 0.66
  normalize: True

model:
  optimize_beta: true
  beta_bins: 5
  n_estimators: 50
  max_depth: 10
  criterion: "squared_error"
  target_quantiles:
    - [0.975, 0.025]
  prediction_step: 1
  window_size: 200

plotting:
  plotting: True
  plotting_seq_len: 200

saving_dir: "./results/spci/sapflux/lstm/${now:%Y-%m-%d_%H-%M-%S_%f}/"
