data:
  data_path: "C:/Users/jayao/Desktop/python_projects/DSCP/data/air-10_prediction/chronos/chronos_air-10_data.pkl"  
  train_ratio: 0.8
  normalize: True


model:
  optimize_beta: true
  beta_bins: 5
  n_estimators: 10
  max_depth: 2
  criterion: "squared_error"
  target_quantiles:
    - [0.950, 0.05]
  prediction_step: 1
  window_size: 100


saving_dir: "C:/Users/jayao/Desktop/spci_test/"

